services:
  node-a:
    image: ghcr.io/nap-it/vanetza-nap:latest
    hostname: node-a
    cap_add:
      - NET_ADMIN
    environment:
      - VANETZA_STATION_ID=10
      - VANETZA_STATION_TYPE=5
      - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:0a
      - VANETZA_INTERFACE=br0
      - VANETZA_USE_HARDCODED_GPS=true
      - VANETZA_LATITUDE=40.630
      - VANETZA_LONGITUDE=-8.660
      - VANETZA_CAM_PERIODICITY=1000
      - START_EMBEDDED_MOSQUITTO=true
      - SUPPORT_MAC_BLOCKING=true
    networks:
      vanetzalan0:
        ipv4_address: 192.168.98.10

  node-b:
    image: ghcr.io/nap-it/vanetza-nap:latest
    hostname: node-b
    cap_add:
      - NET_ADMIN
    environment:
      - VANETZA_STATION_ID=11
      - VANETZA_STATION_TYPE=5
      - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:0b
      - VANETZA_INTERFACE=br0
      - VANETZA_USE_HARDCODED_GPS=true
      - VANETZA_LATITUDE=40.631
      - VANETZA_LONGITUDE=-8.661
      - VANETZA_CAM_PERIODICITY=1000
      - START_EMBEDDED_MOSQUITTO=true
      - SUPPORT_MAC_BLOCKING=true
    networks:
      vanetzalan0:
        ipv4_address: 192.168.98.11

networks:
  vanetzalan0:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.98.0/24
