#!/bin/sh
set -e

export VANETZA_STATION_ID=1
export VANETZA_STATION_TYPE=15
export VANETZA_MAC_ADDRESS="6e:06:e0:03:03:01"
export VANETZA_INTERFACE=br0
export VANETZA_USE_HARDCODED_GPS=true
export VANETZA_CAM_PERIODICITY=2000
export START_EMBEDDED_MOSQUITTO=true
export SUPPORT_MAC_BLOCKING=true
export VANETZA_REMOTE_MQTT_BROKER="${MQTT_HOST:-mqtt-central}"
export VANETZA_REMOTE_MQTT_PORT="${MQTT_PORT:-1883}"
export VANETZA_LATITUDE="${BASE_STATION_LAT:-40.630}"
export VANETZA_LONGITUDE="${BASE_STATION_LNG:--8.660}"
export BASE_STATION_CONTAINER_NAME="base_station"

/entrypoint.sh &
sleep 5
exec python3 /app/main.py
